skip_tags: true
skip_commits:
  files:
    - .travis.yml
install:
  - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --sysupgrade --sysupgrade
  - C:\msys64\usr\bin\pacman --noconfirm --sync --sysupgrade --sysupgrade
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync bash pacman pacman-mirrors msys2-runtime
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-toolchain
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-cmake
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-toolchain
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-cmake
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync make
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-lz4
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-lz4
build_script:
  - set CC=gcc
  - set CXX=g++
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make test"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make release OS=windows ARCH=x86_64"
  - set MSYSTEM=MINGW32
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make clean"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make test"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make release OS=windows ARCH=x86"
artifacts:
- path: build/*.zip
  name: release
deploy:
- provider: GitHub Releases
  auth_token:
    secure: 8bKmFerDMwLIfABa41a6CpaGluVY3D7JEZRKTd1T+or28zGe0Ssw/ZRrdw1Exwf1
