version: 1.0.{build}
skip_tags: true
build_script:
- cmd: >-
    C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --sysupgrade --sysupgrade
    C:\msys64\usr\bin\pacman --noconfirm --sync --sysupgrade --sysupgrade
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync bash pacman pacman-mirrors msys2-runtime
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-toolchain
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-cmake
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-toolchain
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-cmake
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync make
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-lz4
    C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-i686-lz4
    set CC=gcc
    set CXX=g++
    set MSYSTEM=MINGW64
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make"
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make test"
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make release OS=windows ARCH=x86_64"
    set MSYSTEM=MINGW32
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make clean"
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make"
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make test"
    C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && make release OS=windows ARCH=x86"
artifacts:
- path: build\*.zip
  name: Releases
deploy:
- provider: GitHub
  auth_token:
    secure: vdYbDR6bhVD4b/Lwlb5taLlROt0Y1mldXNj3vzcPdE+Q1UDaBYrw/Yb0QKziImcO
  artifact: Releases
